package com.sbhs.swm.util;

import org.springframework.context.annotation.Configuration;

@Configuration
public class CityProvinceNameUtil {
    public String shortenCityName(String city) {
        switch (city) {
            case "AnGiang":
                return "AG";
            case "BàRịa-VũngTàu":
                return "BV";
            case "BạcLiêu":
                return "BL";
            case "BắcGiang":
                return "BG";
            case "BắcKạn":
                return "BK";
            case "BắcNinh":
                return "BN";
            case "BếnTre":
                return "BT";
            case "BìnhDương":
                return "BD";
            case "BìnhĐịnh":
                return "BĐ";
            case "BìnhPhước":
                return "BP";
            case "CàMau":
                return "CM";
            case "CaoBằng":
                return "CB";
            case "CầnThơ":
                return "CT";
            case "ĐàNẵng":
                return "DNa";
            case "Đắklắk":
                return "DL";
            case "ĐắkNông":
                return "ĐNo";
            case "ĐiệnBiên":
                return "DB";
            case "ĐồngNai":
                return "DN";
            case "ĐồngTháp":
                return "DT";
            case "HàNam":
                return "HNa";
            case "HàGiang":
                return "HG";
            case "HàTĩnh":
                return "HT";
            case "HảiDương":
                return "HD";
            case "HảiPhòng":
                return "HP";
            case "HậuGiang":
                return "HGi";
            case "HòaBình":
                return "HB";
            case "HưngYên":
                return "HY";
            case "KhánhHòa":
                return "KH";
            case "KiênGiang":
                return "KG";
            case "KonTum":
                return "KT";
            case "LaiChâu":
                return "LC";
            case "LạngSơn":
                return "LS";
            case "LàoCai":
                return "LCa";
            case "HồChíMinh":
                return "SG";
            case "GiaLai":
                return "GL";
            case "LâmĐồng":
                return "LD";
            case "LongAn":
                return "LA";
            case "NamĐịnh":
                return "ND";
            case "NghệAn":
                return "NA";
            case "NinhBình":
                return "NB";
            case "NinhThuận":
                return "NT";
            case "PhúThọ":
                return "PT";
            case "PhúYên":
                return "PY";
            case "QuảngBình":
                return "QB";
            case "QuảngNam":
                return "QNa";
            case "QuảngNgãi":
                return "QNg";
            case "QuảngNinh":
                return "QN";
            case "QuảngTrị":
                return "QT";
            case "SócTrăng":
                return "ST";
            case "SơnLa":
                return "SL";
            case "TâyNinh":
                return "TN";
            case "TháiBình":
                return "TB";
            case "TháiNguyên":
                return "TNg";
            case "ThanhHóa":
                return "TH";
            case "ThừaThiênHuế":
                return "TTH";
            case "TiềnGiang":
                return "TG";
            case "TràVinh":
                return "TV";
            case "TuyênQuang":
                return "TQ";
            case "VĩnhLong":
                return "VL";
            case "VĩnhPhúc":
                return "VP";
            case "YênBái":
                return "YB";
            case "HàNội":
                return "HN";
            case "BìnhThuận":
                return "BTh";
            default:
                return null;
        }
    }
}
